### ISSUE TITLE
Issue with brew installation 

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/homebrew-tap#4]
Hi,
Attempting to install homebrew-tap leads me to an openssl missing header file (Ubunutu 16.04):
```
...
==> python -c import setuptools... --no-user-cfg install --prefix=/home/milad/.linuxbrew/Cellar/planemo/0.36.1/libexec/vendor --single-version-externally-managed --record=installed.txt
Last 15 lines from /home/milad/.cache/Homebrew/Logs/planemo/11.python:
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/curl
copying python/curl/__init__.py -> build/lib.linux-x86_64-2.7/curl
running build_ext
building 'pycurl' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
/usr/bin/gcc-5 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -Os -w -pipe -march=core2 -isystem/home/milad/.linuxbrew/include -fPIC -DPYCURL_VERSION="7.19.5.3" -DHAVE_CURL_OPENSSL=1 -DHAVE_CURL_SSL=1 -I/home/milad/miniconda2/include/python2.7 -c src/docstrings.c -o build/temp.linux-x86_64-2.7/src/docstrings.o
In file included from src/docstrings.c:4:0:
src/pycurl.h:161:31: fatal error: openssl/crypto.h: No such file or directory
compilation terminated.
error: command '/usr/bin/gcc-5' failed with exit status 1

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/galaxyproject/homebrew-tap/issues

/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
	from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
	from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
	from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /usr/lib/ruby/2.3.0/open-uri.rb:31:in `open'
	from /home/milad/.linuxbrew/Library/Homebrew/utils.rb:621:in `open'
	from /home/milad/.linuxbrew/Library/Homebrew/utils.rb:654:in `issues_matching'
	from /home/milad/.linuxbrew/Library/Homebrew/utils.rb:686:in `issues_for_formula'
	from /home/milad/.linuxbrew/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /home/milad/.linuxbrew/Library/Homebrew/exceptions.rb:218:in `issues'
	from /home/milad/.linuxbrew/Library/Homebrew/exceptions.rb:263:in `dump'
	from /home/milad/.linuxbrew/Library/brew.rb:133:in `rescue in <main>'
	from /home/milad/.linuxbrew/Library/brew.rb:29:in `<main>'
```

**Comment by mmiladi** [comment]
In fact it's planemo installationstep failing, we can ignore this.

**Comment by LouisGil** [comment]
Hi,
Im attempting "brew install planemo" , Im getting this error ValueError: too many values to unpack
[tmp.txt](https://github.com/galaxyproject/homebrew-tap/files/1023223/tmp.txt)

`...
Last 15 lines from /Users/louisgil/Library/Logs/Homebrew/planemo/28.python:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
    reqs = self.dist.requires(self.extras)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
    dm = self._dep_map
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
    if invalid_marker(marker):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
    cls.evaluate_marker(text)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
    env = cls._translate_metadata2(_markerlib.default_environment())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
    for key, value in env
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
    (key.replace('.', '_'), value)
ValueError: too many values to unpack

`

**Comment by hmkim** [comment]
> ==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/planemo/0.38.1/libexec/vendor --single-version-externally-managed --record=installed.txt
> Last 15 lines from /Users/brandon/Library/Logs/Homebrew/planemo/28.python:
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
>     reqs = self.dist.requires(self.extras)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
>     dm = self._dep_map
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
>     if invalid_marker(marker):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
>     cls.evaluate_marker(text)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
>     env = cls._translate_metadata2(_markerlib.default_environment())
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
>     for key, value in env
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
>     (key.replace('.', '_'), value)
> ValueError: too many values to unpack
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> https://github.com/galaxyproject/homebrew-tap/issues
> 

I also have same problem for installing planemo using brew

**Comment by vikyd** [comment]
me too

**Comment by SunLn** [comment]
After uninstall brew, and reinstall it,  I solved this problem. Hope help.
Link:
https://stackoverflow.com/questions/46459152/cant-chown-usr-local-for-homebrew-in-osx-10-13-high-sierra
